github: [Abolfazl74]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:

custom:
  - "bitcoin:bc1q6xgr829nc56vumpjatykn2xhwun6deyrwnqhs8"
  - "litecoin:ltc1q5wjsqxtlssvunwllnktetk3xp5v6pn4wtrmyv6"
  - "ethereum:0xc980245aEF9D2c18261A53D83d30DF943327EcFA"
  - "usdt:0xc980245aEF9D2c18261A53D83d30DF943327EcFA"
